### ISSUE TITLE
点击偏好设置，设置弹出框不时缩成半截

### ISSUE THREAD

**Issue by Batur24** [MoeFE/GoogleTranslate#10]
如下图，点击偏好设置，设置弹出框不时会缩成半截。多点几次就会出来

![test](https://user-images.githubusercontent.com/9591690/30816841-a7ea340a-a249-11e7-836b-193a06c416d2.gif)

**Comment by u3u** [comment]
v2 测试版已发布，欢迎[体验](https://github.com/MoeFE/GoogleTranslate/releases/latest)！🎉
