### ISSUE TITLE
可以切换到其他窗口或者点击到别处时自动关闭吗

### ISSUE THREAD

**Issue by ylzon** [MoeFE/GoogleTranslate#106]
我觉的这个可以改进下 ，或者添加个这样的一个设置，不然按下快捷键打开还要再按一下快捷键才能关闭~
辛苦~~

**Comment by u3u** [comment]
可以呀，非顶部模式失去焦点就会关闭窗口

**Comment by ylzon** [comment]
Sorry打开置顶模式了，那就没问题了

**Comment by u3u** [comment]
( ´･ᴗ･` ) 好的 如果在使用中还发现有其他问题可以继续反馈哦！

**Comment by ylzon** [comment]
好的~
