### ISSUE TITLE
希望能加入右击翻译的功能

### ISSUE THREAD

**Issue by EmpRamses** [MoeFE/GoogleTranslate#109]
就像 Mac 的查询一样，对于选中的单词右击以后可以选择翻译的功能直接显示翻译结果。

**Comment by u3u** [comment]
请具体描述一下右键翻译的功能

**Comment by EmpRamses** [comment]
就像mac的查询一样，对于选中的单词右击以后可以选择翻译的功能直接显示翻译结果。

**Comment by u3u** [comment]
非常抱歉，该应用使用 [Electron](https://electronjs.org/) 构建，无法实现这个功能 😅

**Comment by mantou132** [comment]
可以发布一个配套 webextension API 扩展，以便在浏览器的上下文菜单中添加菜单项，使用 [Native message](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging) 调起应用。

不过这需要~~向系统~~添加一个 [Native manifest](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests#Mac_OS_X) 文件，~~可以用 [sudo-prompt](https://github.com/jorangreef/sudo-prompt) 来获取 root 权限~~。

**Comment by u3u** [comment]
@mantou132 
他的要求应该是在任何地方选中单词然后翻译（目前不是已经支持使用快捷键翻译选中的文本了嘛～）
就像原生词典应用，可以使用三指轻按快速显示翻译结果 🌚
