### ISSUE TITLE
失去焦点后隐藏窗口

### ISSUE THREAD

**Issue by 85Ryan** [MoeFE/GoogleTranslate#11]
现在只能通过点击图标隐藏窗口，如果变为鼠标点击窗口外的其他区域自动隐藏窗口，是否会更好？

**Comment by Batur24** [comment]
可以自定义快捷键，toggle切换，很方便
我用 ctrl + x

**Comment by u3u** [comment]
内个，我想再确认一下，你用的是顶部模式还是非顶部模式？

**Comment by u3u** [comment]
v2 测试版已发布，欢迎[体验](https://github.com/MoeFE/GoogleTranslate/releases/latest)！🎉
