### ISSUE TITLE
如何调试主进程？

### ISSUE THREAD

**Issue by mantou132** [MoeFE/GoogleTranslate#117]
使用 vscode 调试时 js 语法有问题。

使用 node 的 --inspect 参数应该会好用一些，不过不知道在哪里添加这个参数。

**Comment by mantou132** [comment]
手动在 `/node_modules/vue-cli-plugin-electron-builder/index.js` 中启用了调试功能；

启动 `electron` 时添加 `inspect` 参数：`['--inspect', `${outputDir}/background.js`]`
编译 background 时 启用 `sourcemap` ：`mainConfig.devtool('source-map');` 强制执行；

**Comment by u3u** [comment]
可以添加 [`--debug`](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/testingAndDebugging.html#main-process-background-file) 参数调试主进程 ( ๑´•ω•)۶

**Comment by u3u** [comment]
我调整了一些配置，现在调试主进程可以按照这个步骤操作：

1. 使用 `yarn serve:debug` 监听主进程的更改
2. 在 VSCode 的调试面板中选择 Electron Main
3. 使用快捷键 <kbd>F5</kbd> 进入断点调试

**Comment by mantou132** [comment]
@u3u 原来加 `--debug` 后只是自动更新主进程代码，还需要另外启动应用的。
难怪看不到启动应用
