### ISSUE TITLE
使用本地方法判断源语言

### ISSUE THREAD

**Issue by mantou132** [MoeFE/GoogleTranslate#120]
现在使用 [translation.js](https://github.com/Selection-Translator/translation.js) 的 `detect` 方法，但是该方法实际上是使用 Google 的 API，需要进行网络请求

建议使用的本地方法是使用该库：https://github.com/wooorm/franc
他不需要网络请求，他是根据 [UDHR](https://unicode.org/udhr/) 来发现语言的；
该方法速度更快。

不过问题是 franc 的到的语言代码是 [ISO 639-3](https://iso639-3.sil.org/code_tables/639/data) 规格，需要映射到 zh-CN (这是什么规范？)

**Comment by u3u** [comment]
谷歌翻译使用的是 [ISO-639-1](https://cloud.google.com/translate/docs/languages) 代码，似乎可以使用 [nodejs-langs](https://github.com/adlawson/nodejs-langs) 来转换

**Comment by mantou132** [comment]
franc 识别单词准确率太低了。
