### ISSUE TITLE
翻译目标语言添加“自动选择”

### ISSUE THREAD

**Issue by mantou132** [MoeFE/GoogleTranslate#123]
当目标语言选择“自动”时：

- 源语言输入中文（繁简）时自动选择目标语言为英文
- 源语言输入中文（繁简）以外的语言时自动选择目标语言为中文

**Comment by mantou132** [comment]
虽然现在有识别源语言等于目标语言时自动切换源/目标语言就已经很方便了。

 但是这样会造成源语言“自动”变为失效。

**Comment by u3u** [comment]
我觉得这样不太符合逻辑诶，目前也没有任何一款翻译软件会让目标语言选择自动检测 ( ꒪﹃ ꒪)
目前自动检测也并非完全没有用处，当用户选择自动检测时无论他输入什么语言都会被翻译成目标语言
