### ISSUE TITLE
窗口位置错误

### ISSUE THREAD

**Issue by mantou132** [MoeFE/GoogleTranslate#125]
当托盘的其他图标尺寸改变时，应用托盘图标的位置也会随之改变。

是否可以使用 [`Tray.getBounds()`](https://electronjs.org/docs/api/tray#traygetbounds-macos-windows) 避免这个问题

<img width="451" alt="screen shot 2018-09-07 at 09 41 27" src="https://user-images.githubusercontent.com/3841872/45193747-46e97e00-b282-11e8-924f-0c3b33d4455e.png">

**Comment by u3u** [comment]
menubar 内部就是通过 [`Tray.getBounds()`](https://electronjs.org/docs/api/tray#traygetbounds-macos-windows) 实现的

https://github.com/MoeFE/GoogleTranslate/blob/15bdc95ebc12d7b1c8571346d002fffe8f46a81f/src/main/lib/menubar/index.js#L126

这种情况没法避免，因为你按住 <kbd>command</kbd> 并拖动图标也可以直接改变图标顺序
那么只有在窗口 `mouseenter` 的时候重新计算一下窗口坐标
这里将 `window.focus()` 改成 `ipcRenderer.send('showWindow')` 应该就可以了

https://github.com/MoeFE/GoogleTranslate/blob/15bdc95ebc12d7b1c8571346d002fffe8f46a81f/src/renderer/App.tsx#L62-L66

**Comment by mantou132** [comment]
把 `cachedBounds` 去掉就行了啊，即每次显示 window 都计算一次 tray 的位置，`Tray.getBounds()` 应该没有性能问题

// 窗口已经打开的情况下托盘发生了变化有没有办法检测到？

**Comment by u3u** [comment]
> 每次显示窗口都计算一次托盘的位置

点击托盘时会带上当前托盘的 `bounds` 数据，`cachedBounds` 是作为备选的

https://github.com/MoeFE/GoogleTranslate/blob/15bdc95ebc12d7b1c8571346d002fffe8f46a81f/src/main/lib/menubar/index.js#L79-L84

> 窗口已经打开的情况下托盘发生了变化有没有办法检测到？

这个据我所知没办法检测
