### ISSUE TITLE
托盘图标和系统其他图标不协调

### ISSUE THREAD

**Issue by mantou132** [MoeFE/GoogleTranslate#126]
现在的图标显得尺寸过大。和系统其他图标不协调；

<img width="442" alt="screen shot 2018-09-06 at 23 24 59" src="https://user-images.githubusercontent.com/3841872/45167609-1840b880-b22c-11e8-9961-2ff1dab583ce.png">

**Comment by u3u** [comment]
我感觉还好呀，系统的 WI-FI 图标也比较大，你是和 Shadowsocks 进行对比的吧
这个图标我如果没记错的话好像是从 iOS 版的 Google 翻译中提取出来的，我也不会改 (´°д°`)

**Comment by mantou132** [comment]
好像周围的空间有点少。

<img width="409" alt="screen shot 2018-09-07 at 10 51 36" src="https://user-images.githubusercontent.com/3841872/45195835-173f7380-b28c-11e8-9c0c-b29813abeab0.png">
改成这样也没什么差别。

**Comment by u3u** [comment]
哇 好像是的，平常没怎么注意 😅
但我感觉现在的图标更好看 可以尝试修改现在的图标尺寸 🌚
