### ISSUE TITLE
使用暗色主题时，菜单栏图标不可见

### ISSUE THREAD

**Issue by metorm** [MoeFE/GoogleTranslate#13]
好像是因为图标前景色恰好是黑色，不能切换。
小问题，有空可以处理一下。作者威武！

**Comment by u3u** [comment]
😂 其实我之前已经发现了 打算有时间重写一下

**Comment by u3u** [comment]
v2 测试版已发布，欢迎[体验](https://github.com/MoeFE/GoogleTranslate/releases/latest)！🎉
