### ISSUE TITLE
网络繁忙，请稍后再试

### ISSUE THREAD

**Issue by webmote** [MoeFE/GoogleTranslate#14]
API调用貌似不稳定，切换了几个翻译器，貌似都有问题

**Comment by u3u** [comment]
我这边是好的呢 检查一下你是否开了代理或者代理服务器出现问题
国内的谷歌翻译是不需要代理也能用的 你试试访问 https://translate.google.cn/ 能打开吗？

**Comment by liangxiaorui** [comment]
我也有这样的情况，开了代理服务器Google（非国内的）反而还不能用，希望能改进或者允许手工设置代理？谢谢～

**Comment by ylzon** [comment]
目测是除了有道翻译以外，其他三种翻译方式都没有配置api key，百度翻译还好办，google的要注册Cloud Platform才能申请

**Comment by u3u** [comment]
v2 测试版已发布，欢迎[体验](https://github.com/MoeFE/GoogleTranslate/releases/latest)！🎉
