### ISSUE TITLE
提几个改进建议

### ISSUE THREAD

**Issue by jiam9700** [MoeFE/GoogleTranslate#15]
1、实现像有道词典一样鼠标停留出翻译的功能

2、换用其他搜索方式的时候最好是永久换用

3、用诸如有道词典一类的系统的时候如果能出详细释义是最好的

4、感谢楼主提供给大家方便的app

**Comment by u3u** [comment]
取词/划词翻译目前我在 Electron [文档](https://electronjs.org/docs)中没有找到相关 API 可以实现
其他的会在 2.0 版本中改进，感谢您提的建议！

**Comment by u3u** [comment]
v2 测试版已发布，欢迎[体验](https://github.com/MoeFE/GoogleTranslate/releases/latest)！🎉
