### ISSUE TITLE
Google翻译/百度翻译无法使用

### ISSUE THREAD

**Issue by Mother-Ship** [MoeFE/GoogleTranslate#17]
Google提示网络繁忙，已经挂了梯子，https://translate.google.com/ 访问正常；

百度则提示没有有效的返回结果。

另外在mac 10.13.4上，点击设置开机启动的开关会卡住……意外设置成功后要取消也会卡住。

**Comment by u3u** [comment]
v2 测试版已发布，欢迎[体验](https://github.com/MoeFE/GoogleTranslate/releases/latest)！🎉

**Comment by mantou132** [comment]
我这里也经常会失败。就连百度也会失败

**Comment by u3u** [comment]
@mantou132 关于这个问题已经在[常见问题](https://github.com/MoeFE/GoogleTranslate#faq)中详细描述了

**Comment by mantou132** [comment]
@u3u  主要是谷歌翻译的页面却可以用。为此我自己弄了一个分支，直接使用谷歌翻译的 webapp

![screen shot 2018-09-08 at 07 38 32](https://user-images.githubusercontent.com/3841872/45247439-33015300-b33a-11e8-8348-c47f593c3088.png)

特性有：

- 稳定的翻译结果
- 自动调整目标语言
- 选择文本使用快捷键打开窗口并翻译
- 有一个配套的浏览器扩展，直接浏览器右键菜单翻译
- 快捷键朗读【不会做】

**Comment by u3u** [comment]
@mantou132 那你有没有看不可用时网络请求的响应结果是什么
(≧▽≦) 你这个截图不错诶，是直接内嵌了谷歌翻译的网页喵？

**Comment by mantou132** [comment]
提示流量不正常。
是啊，使用 <webview> 标签，preload 自己插入脚本。
https://github.com/mantou132/GoogleTranslate
