### ISSUE TITLE
重新查询，按删除键输入框失去聚焦

### ISSUE THREAD

**Issue by Batur24** [MoeFE/GoogleTranslate#3]
步骤：
1，输入hello，按回车键
2，点击输入框，重新编辑查另一个单词
3，按删除键
结果：
失去聚焦
期望：
不失去聚焦

**Comment by u3u** [comment]
我居然没测出来 尴尬

**Comment by Batur24** [comment]
这项目很好，希望能越来越完善

**Comment by u3u** [comment]
会的！感谢支持！这个 BUG 已经修复了
等我再把 #2 解决后一起发布版本

**Comment by Batur24** [comment]
嗯嗯，我是来向你学习的，等你commit了，我看看你做了哪些改动 
:-)

**Comment by Batur24** [comment]
建议回车查询后，聚焦还在查询单词的输入框

因为一般情况下，用户拼错单词、翻译没查出来，或者需要连续查询，如果都要用鼠标重新点击，比较麻烦

**Comment by u3u** [comment]
我想的是 查询单词后让查询结果获得焦点 这样就可以直接 <kbd>cmd + a</kbd> 复制结果了
我可以增加一个快捷键让源语言输入框获得焦点
或者在新增按 <kbd>cmd + enter</kbd> 查询 让焦点保持在当前输入框内
您觉得怎样合适呢？

**Comment by Batur24** [comment]
刚才不知道为什么目标翻译的输入框没有焦点，现在好了。
这样也挺好，用`shift+tab`就可以让焦点回到源输入框了。

**Comment by u3u** [comment]
源语言选的是自动检测的时候目标不允许获得焦点
因为在源语言不是检测语言时 在目标输入框内输入会自动掉换位置 自动检测语言不能掉换为目标
噗 我居然忘记有 <kbd>shift + tab</kbd> 这个快捷键了

**Comment by Batur24** [comment]
一开始我以为在目标输入框编辑自动调换位置是一个bug，才发现这是一个非常棒的功能。👍👍
