### ISSUE TITLE
不能输入中文

### ISSUE THREAD

**Issue by Batur24** [MoeFE/GoogleTranslate#4]
步骤：
1、中文翻译英语，输入中文
结果：
不显示输入结果
期望：
显示输入的中文结果

**Comment by u3u** [comment]
![image](https://user-images.githubusercontent.com/20062482/30728691-62a59c40-9f1f-11e7-9331-72bb5a237d97.png)
有截图吗 我测试是好的 你输入的中文是啥

**Comment by Batur24** [comment]
我在开发模式npm run dev不行，用下载的安装包就没问题。
为什么呢？

**Comment by u3u** [comment]
有提示什么错误嘛 你打开开发人员工具 控制台看看 然后看一下请求

**Comment by u3u** [comment]
我开发模式也没有问题

**Comment by Batur24** [comment]
控制台没有任何信息，就是输入不进去。我用的是mac自带的输入法

在终端上报了下面的信息，不知道有没有关系
```
Electron -------------------

  2017-09-22 12:03:10.692 Electron Helper[58405:1704812] Couldn't set selectedTextBackgroundColor from default ()
```

**Comment by Batur24** [comment]
另外，在我的开发模式下，粘贴也不能用，中英文粘贴都不行

控制台显示我的开发工具不能连接页面

![image](https://user-images.githubusercontent.com/9591690/30728984-b91578c4-9f8e-11e7-9ff9-6b23ab42a3d8.png)

**Comment by u3u** [comment]
我一会重新克隆一个到本地试试

**Comment by u3u** [comment]
我刚才重新克隆了一个测试也没有问题
你是用什么安装的模块 Node 和 NPM 版本是多少

**Comment by Batur24** [comment]
我直接npm install的, npm版本4.6.1，node版本8.0.0

**Comment by u3u** [comment]
那就奇怪了，我 NPM 版本 5.0.0， Node 版本 8.0.0
你 NPM 有用别的源吗 我是用 `taobao - https://registry.npm.taobao.org/` 安装的
要不你也试试换淘宝源重新安装一下模块QAQ

**Comment by Batur24** [comment]
我也是用淘宝源安装的，我等下删掉重新安装试试
QAQ是什么意思？

**Comment by u3u** [comment]
噗 这个是表情

**Comment by Batur24** [comment]
`rm -rf node_modules` 重新 `npm install` 还是不能输入中文。不知道什么问题

**Comment by u3u** [comment]
要不我把我本地安装好能正常运行的工程打包发给你试试
如果还有问题的话估计就是你的 NPM 问题了 尝试升级到 5.0.0 和我一样的版本试试

**Comment by u3u** [comment]
https://share.weiyun.com/c46c1218e3985e082259dfe364b22f87
你下载这个解压后试试

**Comment by Batur24** [comment]
好的，谢谢！

**Comment by u3u** [comment]
你用这个能正常运行吗

**Comment by Batur24** [comment]
居然是tmux的问题！这太奇怪了！

我用自带的终端运行你的包没问题，我在iterm的tmux下运行有问题，退出tmux没有问题。
退出tmux，我运行clone下来的包也没问题了。

这个有点不可思议。

**Comment by u3u** [comment]
😂 解决了就行

**Comment by Batur24** [comment]
嗯嗯
