### ISSUE TITLE
请问是否有可能支持Apple M1系列？

### ISSUE THREAD

**Issue by zhiweilong** [MoeFE/GoogleTranslate#489]
感谢作者的作品，用了快2年了。笔记本换成M1之后发现用不了？是否有计划支持M1？谢谢！

**Comment by yukiho1962** [comment]
M1是可以用的，我现在就在用呢

**Comment by zhiweilong** [comment]
现在可以使用了，不知道是不是和网络（VPN，防火墙）有关。没有任何额外设置，就是现在网络直接能够打开Google。
