### ISSUE TITLE
播放单词声音的快捷键似乎不能用

### ISSUE THREAD

**Issue by Batur24** [MoeFE/GoogleTranslate#5]
我试了下<kbd>cmd + shift + 1</kbd>不能播放源语言
`2`也不能播放目标语言

<kbd>shift + 1</kbd>不就是`!`了？

**Comment by u3u** [comment]
奇怪我之前测试是正常的 我看看

**Comment by u3u** [comment]
嗨呀 有一次重构的时候忘记替换快捷键对应的方法了

**Comment by Batur24** [comment]
<kbd>cmd + shift + 1</kbd> 这个快捷键是不是有点别扭？

**Comment by u3u** [comment]
😅 这个是我参考别的 APP 的，我一般都是用鼠标点，如果换成 <kbd>alt + 1</kbd> 会不会方便点？

**Comment by Batur24** [comment]
`alt + 1`不错
如果经常用，键盘比鼠标方便很多

**Comment by u3u** [comment]
行 那我再发一个版本

**Comment by u3u** [comment]
<kbd>ctrl</kbd> 和 <kbd>alt</kbd> 键都和系统有冲突 
<kbd>alt + 数字</kbd> 会输出这些 ¡™£¢§ˆ¶•ªº–≠
<kbd>ctrl + 2</kbd> 则会切换桌面

所以貌似别的程序设计的快捷键还是有依据的。。

**Comment by Batur24** [comment]
可不可以把播放声音和修改语言的快捷键调换一下，一般情况下不会经常换语言，但可能会经常看某个单词怎么发音的？
你觉得呢？

**Comment by u3u** [comment]
好的，那等 #6 修复后一起发布一个版本
