### ISSUE TITLE
快捷键建议

### ISSUE THREAD

**Issue by stickmy** [MoeFE/GoogleTranslate#54]
目前快捷键在使用组合键时，比如：`option + q` ，会变成对应的特殊字符，如图：

![](https://blog-1252181333.cossh.myqcloud.com/blog/032417.png)

**Comment by u3u** [comment]
是的，这个问题在 2.0 版本中已经修复了 😄

https://github.com/MoeFE/GoogleTranslate/blob/acb597500987e286e985ca6cf1955ea7052cb348/src/renderer/components/InputShortcutKeys.tsx#L186-L210

**Comment by stickmy** [comment]
给力

**Comment by u3u** [comment]
v2 测试版已发布，欢迎[体验](https://github.com/MoeFE/GoogleTranslate/releases/latest)！🎉

**Comment by imwhite** [comment]
![23CD0972-06B0-4941-8E58-18DAEDC3D5F7](https://user-images.githubusercontent.com/5457297/63139222-18d2f900-c010-11e9-95f0-1d8b52b389dc.png)
