### ISSUE TITLE
功能需求

### ISSUE THREAD

**Issue by shaneing** [MoeFE/GoogleTranslate#9]
作者有时间可以考虑下呗：

- 代理，至少 http
- 选中要翻译的文本有 google 翻译的快捷按钮

**Comment by u3u** [comment]
代理应该直接走系统代理的，我开 SS 是没问题的
如果你不能访问 Google 你可以在偏好设置中将翻译引擎设置为国内的 Google 试试

![image](https://user-images.githubusercontent.com/20062482/30770649-7e8026ec-9ffb-11e7-940f-8aa59737de0d.png)

**Comment by u3u** [comment]
选中翻译指的是在系统任何程序中选中文本显示一个翻译悬浮窗吗 就是划词翻译？
这个我不确定能不能实现 取决于 Electron 是否可以获取到系统当前选中的文本

**Comment by shaneing** [comment]
为啥我不行呢。不知道 electron 有没有提供这样的 api

**Comment by u3u** [comment]
接口地址是 HTTPS 协议，你应该还需要设置安全网页代理（HTTPS）

**Comment by u3u** [comment]
https://ipinfo.io/
修改之后访问这个地址查看是否生效

**Comment by shaneing** [comment]
<img width="390" alt="2017-09-23 2 41 23" src="https://user-images.githubusercontent.com/14818134/30770856-6e557700-a06d-11e7-9398-dc4325646429.png">

**Comment by u3u** [comment]
你访问 Google 正常吗

**Comment by shaneing** [comment]
奇怪。又失败了，我 ss 很快。。。

**Comment by u3u** [comment]
用自动代理试试呢 我用的是这个

![image](https://user-images.githubusercontent.com/20062482/30770941-87c43458-a002-11e7-8b1a-8c600dcaf349.png)

**Comment by shaneing** [comment]
不试了，不知道问题出哪里，哈哈。你是搞前端的么

**Comment by u3u** [comment]
是的

**Comment by u3u** [comment]
v2 测试版已发布，欢迎[体验](https://github.com/MoeFE/GoogleTranslate/releases/latest)！🎉
